# -*- coding: utf-8 -*-
"""cac_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ToH7RgCb16ZFSHNUTxa3MX-A3gm-lOYl
"""

import pandas as pd
import matplotlib.pyplot as plt

# 1. Set up the data
data = {
    "quarter": ["Q1", "Q2", "Q3", "Q4"],
    "cac": [230.71, 226.26, 228.59, 232.39],
}
df = pd.DataFrame(data)

industry_target = 150

# 2. Compute metrics
df["target"] = industry_target
df["variance_vs_target"] = df["cac"] - df["target"]
df["pct_over_target"] = df["variance_vs_target"] / df["target"] * 100

avg_cac = df["cac"].mean()
print("Average CAC:", round(avg_cac, 2))  # should print 229.49

# 3. Summary stats you can mention in README
overall_variance = avg_cac - industry_target
pct_overall_over_target = overall_variance / industry_target * 100

print("Overall variance vs target:", round(overall_variance, 2))
print("Overall % over target:", round(pct_overall_over_target, 1))

# 4. Plot CAC per quarter vs target
plt.figure(figsize=(8, 5))

plt.plot(df["quarter"], df["cac"], marker="o", label="Actual CAC (2024)")
plt.axhline(y=industry_target, linestyle="--", label="Industry Target (150)")

for i, v in enumerate(df["cac"]):
    plt.text(df["quarter"][i], v + 1, f"{v:.1f}", ha="center", fontsize=8)

plt.title("Customer Acquisition Cost (CAC) – 2024 by Quarter")
plt.xlabel("Quarter")
plt.ylabel("CAC")
plt.legend()
plt.grid(True, linestyle=":", alpha=0.5)

plt.tight_layout()
plt.savefig("cac_trend.png", dpi=150, bbox_inches="tight")
plt.show()

from google.colab import files
files.download("cac_trend.png")

